# Generated by Django 4.1.4 on 2023-09-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status post'},
        ),
    ]
